# Service definition for 'instance' 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.gitlab.com/app: acuantgo-instance
    app.gitlab.com/env: qa
  labels:
    app: acuantgo-instance
  name: acuantgo-instance
  namespace: acuant-go
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acuantgo-instance
  template:
    metadata:
      annotations:
        app.gitlab.com/app: acuantgo-instance
        app.gitlab.com/env: qa
      creationTimestamp: null
      labels:
        app: acuantgo-instance
    spec:
      containers:
      - name: acuantgo-instance
        image: 858475722663.dkr.ecr.us-east-1.amazonaws.com/hub-instance-design-studio-acountgo:v0.1.60
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-config-unknown-v0.0-latest
        - secretRef:
            name: app-secret-unknown-v0.0-latest
        ports:
        - containerPort: 5005
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: instance-registry-creds
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: acuantgo-instance-service
  namespace: acuant-go
  labels:
    app: acuantgo-instance
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: 'TCP'
    alb.ingress.kubernetes.io/healthcheck-path: '/'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '5'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '2'
    alb.ingress.kubernetes.io/healthcheck-port: 'traffic-port'
    alb.ingress.kubernetes.io/healthcheck-protocol: 'TCP'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/success-codes: '200'
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: acuantgo-instance
    deployment: unknown-v0.0-latest
