apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-unknown-v0.0-latest
  namespace: acuant-go
data:
  DESIGN_VERSION: "v0.0.9"
  INSTANCE_VERSION: "v0.1.60"
  PROVISIONING_VERSION: "v0.0.11"
  WEBSTORE_VERSION: "latest-20201412"
  K8S_NAMESPACE: "acuant-go"
  SHORT_BRANCH_NAME: "unknown-v0.0"
  DEPLOY_COLOR: "latest"
  K8S_LABEL_DEPLOYMENT: "unknown-v0.0-latest"
  CONFIG_MAP_NAME: "app-config-unknown-v0.0-latest"
  SECRET_NAME: "app-secret-unknown-v0.0-latest"
  DESIGN_SERVICE: "acuantgo-design"
  INSTANCE_SERVICE: "acuantgo-instance"
  PROVISIONING_SERVICE: "acuantgo-provisioning"
  WEBSTORE_SERVICE: "acuantgo-webstore"
  INSTANCE_PORT: "5005"
  PROVISIONING_PORT: "5003"
  WEBSTORE_PORT: "8443"
  DESIGN_PORT: "8006"
  SERVICE_PORT: "9090"
  SCRIPT_ENV: "acuant-k8s"
  INSTANCE_SERVICE_URL: "default-host-instance"
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT: "858475722663"
  AWS_ECR_REGISTRY: "localhost:5001"
  DESIGN_IMAGE_REPO: "hub-design-studio-acuantgo"
  INSTANCE_IMAGE_REPO: "hub-instance-design-studio-acountgo"
  PROVISIONING_IMAGE_REPO: "acuantgo-provisioning-service"
  WEBSTORE_IMAGE_REPO: "acuantgo-webstore"
  KAFKA_SERVICE_URL: "host.docker.internal:9092"
  REDIS_SERVICE_URL: "host.docker.internal:6379"
  TWILIO_SERVICE_URL: "https://api.twilio.com/2010-04-01/Accounts//Messages.json"
  ASSUREID_SERVICE_URL: "1.1.1.1"
  IDENTITYMIND_SERVICE_URL: "1.1.1.1"
  DESIGN_IMAGE: "localhost:5001/hub-design-studio-acuantgo:v0.0.9"
  INSTANCE_IMAGE: "localhost:5001/hub-instance-design-studio-acountgo:v0.1.60"
  PROVISIONING_IMAGE: "localhost:5001/acuantgo-provisioning-service:v0.0.11"
  WEBSTORE_IMAGE: "localhost:5001/acuantgo-webstore:latest-20201412"
  BITBUCKET_API_URL: "https://api.bitbucket.org/2.0/repositories"
  DESIGN_VALIDATE_USER_TOKEN: "false"
  GIT_TARGETS_REPO: "acuant/hub-client-targets-acuantgo-dev"
  GIT_TARGETS_BRANCH: "master"
  BITBUCKET_API_URL: "https://api.bitbucket.org/2.0/repositories"
  BITBUCKET_API_USR: "alexey_chudinov"
  PROVISIONING_API_DOMAIN: "acuantgo-dev.com"
  PROVISIONING_API_DISABLED: "true"
  MONGODB_CLUSTER_URL: "default"
  MONGODB_DATABASE_NAME: "acuantGoProvisioningDB"
  MONGODB_URL: "mongodb://host.docker.internal/acuantGoProvisioningDB"
  JWT_KEY: "6CAEC7B9CFF4B59ACC8A713FDDA3CB7A20B894704E8AFF9517DFEF60FCBB19CC"
  SSL_KEY_STORE_PATH: "file:/security/hub-keystore.jks"
  SSL_KEY_STORE_PASSWORD: "zenoohub"
  SSL_TRUST_STORE_PATH: "file:/security/cacerts-zenoo.jks"
  SSL_TRUST_STORE_PASSWORD: "znnc0nn21wqcnnt22"
  IDM_DESIGNSTUDIO_API_URL: "https://go-unknown-v0.0.acuant.com/api/designstudio"
  IDM_DESIGNSTUDIO_USR: "adminacuant"
  IDM_CREDENTIALS_API_STG_URL: "https://pluginst.identitymind.com/test/getcredential"
  IDM_CREDENTIALS_API_STG_USR: "acuantgo"
  IDM_CREDENTIALS_API_PRD_URL: "https://pluginst.identitymind.com/test/getcredential"
  IDM_CREDENTIALS_API_PRD_USR: "acuantgo"
  IDM_EDNA_US_STG_URL: "https://staging.identitymind.com"
  IDM_EDNA_US_SBX_URL: "https://sandbox.acuant.com"
  IDM_EDNA_US_DMO_URL: "https://demo.acuant.com"
  IDM_EDNA_US_PRD_URL: "https://edna.identitymind.com"
  IDM_EDNA_EU_STG_URL: "https://eu.staging.acuant.com"
  IDM_EDNA_EU_PRD_URL: "https://eu.edna.acuant.com"
  MIXPANEL_ID: "e66fc206fb9a9d85edb642d28ec70b5d"
  MIXPANEL_API_URL: "https://mixpanel.com/api/2.0"
  MIXPANEL_PROJECT_ID: "2496369"
  MIXPANEL_FUNNEL_ID: "15147505"
  MIXPANEL_WORKSPACE_ID: "3037937"
  MIXPANEL_BOOKMARK_ID: "26963284"
  MIXPANEL_FUNNEL_START_DATE: "2021-01-01"
  COOKIE_EXPIRATION: "3600"
  COOKIE_SECURE: "false"
  COOKIE_HTTP_ONLY: "true"
  COOKIE_PUBLIC_KEY: "3676397924423F4528482B4D6251655468576D5A7134743777217A25432A4629"
  COOKIE_SAME_SITE: "none"
  COOKIE_SECURE_PROXY: "true"
  ANALYTICS_INTERCOM: "null"
  ANALYTICS_API_URL: "https://go-stg.acuant.com/api/reports"
  CONTAINER_PROTOCOL: "TCP"
  ENVIRONMENT_NAME: "dev"
  EKS_WORKER_NODE_GROUP: "eks-worker-node-group"
  AWS_HOSTED_ZONE: "acuantgo-qa.com"
  AWS_CLOUDFRONT_CLEANUP_RATE: "30000"
  AWS_CLOUDFRONT_CLEANUP_ENABLED: "true"
  AWS_HOSTED_ZONE_ID: "Z08166051ZOOKT5QKBB09"
  AWS_CLOUDFRONT_VIEWER_CERTIFICATE: "arn:aws:acm:us-east-1:858475722663:certificate/9243d124-0a2b-4940-8543-7e92997fb692"
